# Example configuration for local development/testing

# Local notebook source
notebook_source: "/Users/username/notebooks"

# Glue Catalog configuration
glue_catalog:
  account_id: "123456789012"
  region: "us-west-2"
  databases: ["test_db", "analytics_db"]

# OpenSearch configuration for local testing
opensearch:
  endpoint: "localhost:9200"
  region: "us-west-2"
  index_name: "spira-test"
  use_ssl: false
  verify_certs: false

# Models configuration
models:
  offline_model: "anthropic.claude-3-haiku-20240307-v1:0"
  online_model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  embedding_model: "amazon.titan-embed-text-v2:0"
  region: "us-west-2"

# Smaller scale for testing
processing:
  max_workers: 3
  batch_size: 20
  chunk_size: 500
  similarity_threshold: 0.6